enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[Music-Extended]
enabled = true
app-name = "Music"
patches-source = "anddea/revanced-patches"
patches-version = "latest"
cli-source = "inotia00/revanced-cli"
integrations-source = "inotia00/revanced-integrations"
cli-version = "latest"
integrations-version = "latest"
rv-brand = "ReVanced Extended" 
build-mode = "both"
arch = "both"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
patches-version = "latest"
cli-source = "inotia00/revanced-cli"
integrations-source = "inotia00/revanced-integrations"
cli-version = "latest"
integrations-version = "latest"
rv-brand = "ReVanced Extended"
build-mode = "both"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"